### ISSUE TITLE
MRAC matching is broken

### ISSUE THREAD

**Issue by NumerousHats** [NumerousHats/authoritizer#8]
Traceback (most recent call last):
  File "authoritizer.py", line 120, in runMatching
    scores = sorted(scores, key=lambda score: -score[1])[0:10]
  File "authoritizer.py", line 120, in <lambda>
    scores = sorted(scores, key=lambda score: -score[1])[0:10]
TypeError: bad operand type for unary -: 'NoneType'

**Comment by NumerousHats** [comment]
Disabled option for now.
